#+TITLE: Verificação formal de software
#+AUTHOR: Leonardo Ribeiro Santiago (120036072)
#+OPTIONS: toc:nil date:nil

#+LaTeX_CLASS: article
#+LaTeX_CLASS_OPTIONS: [a4paper]
#+LaTeX_HEADER: \usepackage[portuguese]{babel}
#+CITE_EXPORT: natbib

#+BIBLIOGRAPHY: references.bib

#+BEGIN_abstract
Verificação formal de software é o campo da computação que se preocupa com o ofício de matematicamente provar propriedades de um programa com segurança e corretude, assegurando que ele está conforme especificações pre-determinadas. Esse método possui inúmeros casos de sucesso, como o compilador de C /CompCert/, o micro-kernel /seL4/, o algoritmo de consenso distribuido /Raft/ e provas matemáticas famosas, como o teorema das 4 cores, o teorema de Feit-Thompson e, recentemente, o valor de $BusyBeaver(5)$. Apesar disso, o uso desse na indústria ainda é escasso, e não corresponde à sua capacidade de produzir programas de qualidade com garantias de corretude. Este trabalho tem o objetivo de explorar a história e as fundações teóricas da área de verificação de software, as ferramentas e linguagens existentes, e por fim, a produção de uma prova verificada de uma estratégia de xadrez, de forma a validar a segurança e revelar as dificuldades no processo de criação.
#+END_abstract

* Introdução

# https://ntrs.nasa.gov/api/citations/19890006914/downloads/19890006914.pdf

O processo de desenvolvimento de /software/ pode ser separado em dois problemas distintos: a de validação, que pretende assegurar que o programa a ser desenvolvido resolve um problema desejado, e a de verificação, que assegura que o programa desenvolvido implementa as especificações formadas na fase de validação.

A área de validação é tradicionalmente tópico de estudo das práticas de modelagem de /software/, que tem como produção gráficos conceituais, modelos e regras de negócio, que devem ser utilizados para desenvolver o programa.

Apesar de muito esforço ser colocado em resolver o problema da validação, a verificação muitas vezes é reduzida a testes. Ainda que sejam uma ferramenta útil, esses não conseguem garantir que um programa adere de fato aos modelos criados na fase de validação, visto que não possuem o rigor matemático suficiente. Pela sua praticidade, são utilizados para achar errors triviais e proteger-se contra regressões, mas, de forma geral, é relativamente comum um programa passar nos testes e ainda sim não estar correto em sentido estrito.

Verificação formal de software descreve o conjunto de axiomas, regras e práticas que permitem construir provas sobre o comportamento de programas de computador. Através do formalismo matemático, é possível conferir a um software fortes garantias de corretude, assegurando-se que está conforme as especificações.

# https://compcert.org/motivations.html

O compilador de C /CompCert/ [cite:@2006-Leroy-compcert] é um dos maiores expoentes dessa área. Ao desenvolver um modelo formal de memória contendo ponteiros, o compilador permite não somente descrever transformações entre programas, mas também provar matematicamente que tais transformações preservam a mesma semântica que o programa original. Dessa forma, torna-se trivial introduzir otimizações que simplificam o programa garantindo que essas não introduzem /bugs/ no programa original, visto que o cerne do compilador é manter a verificada prova de que o resultado final do código fonte é semânticamente igual ao binário compilado. De fato, [cite:@Yang2011] mostraram que, dentre todos os compiladores de C tradicionais, incluindo =gcc= e =clang=, o /CompCert/ fora o único a não apresentar sequer um /bug/ de compilação após testes minuciosos.











* Contexto histórico

A história da verificação formal pode ser traçada diretamente da história da computação, tendo origens na empreitada de Hilbert de descrever uma máquina teórica que seria capaz de deduzir  qualquer afirmação se é universalmente verdadeira ou falsa  - conhecido como /Entscheidungsproblem/. Para determinar isso, fez-se necessário primeiro determinar o que constitui um algoritmo.

Em 1910, procurando essa resposta, Bertrand Russel objetivou construir um sistema donde todas equações matemáticas válidas poderiam ser derivadas, utilizando os fundamentos da teoria dos conjuntos introduzida por Cantor. Para Russel, um algoritmo seria uma sequência de deduções lógicas válidas dentro de um sistema axiomático. Tal empreitada provou-se complicada, visto que o problema da auto referência causou múltiplas inconsistências fundamentais dentro dessa formulação, a mais famosa dessas conhecida como o paradoxo de Russel. O cerne desse paradoxo consiste em construir um conjunto $S$ que contém todos os conjuntos que não contém a si mesmo, fazendo com que a proposição $S \in S$ não tenha resposta válida.

Em sua obra prima /Principia Mathematica/, Russel rudimentarmente esboçou o que pode ser considerado o primeiro sistema de tipos, posteriormente descrito por Kleene como "sistema de tipos ramificado", em sua definição de teoria dos conjuntos, como alternativa aos axiomas oferecidos por Cantor, para evitar o problema da auto referência, tornando o sistema consideravelmente mais complexo ao introduzir uma hierarquia de universos, ao invés de um único conjunto universo. Concomitantemente, Zermelo e Fraenkel ofereceram uma axiomatização alternativa consideravelmente mais simples evitando o problema da auto referência, conhecidas como ZFC, que até hoje pode ser considerada como a fundação da matemática moderna.

Em 1931, Kurt Gödel demonstrou que todo sistema complexo o suficiente para conter os números naturais contém declarações válidas que não podem ser provadas pelo sistema, conhecido como teorema da incompletude - o que inclui tanto o sistema de Russel e o ZFC. Três anos depois, Gödel formalizou uma classe de funções conhecidas como funções recursivas gerais, dando sua própria tentativa de responder o que seria um algoritmo: qualquer função recursiva que esteja na classe que ele descrevera. 

Em 1936, Alonzo Church desenvolveu o cálculo lambda para descrever funções no contexto de teoria dos números, e mostrou que tal sistema é complexo o suficiente para codificar números e aritmética. Para Church, um algoritmo seria qualquer função definível no sistema do cálculo lambda. Utilizando esse sistema, Church foi capaz de provar que o desafio original proposto por Hilbert era impossível, mostrando que o problema de determinar se uma expressão bem formada do cálculo lambda tem uma forma "beta normal" é impossível.

No mesmo ano, Alan Turing desenvolveu outro modelo para computar funções, conhecidas hoje em dia como máquinas de Turing, para computar programas manipulando símbolos em uma fita, e mostrou que seu sistema também era capaz de codificar funções, números e aritmética. Para Turing, um algoritmo seria uma tabela de transições que descrevem uma máquina. Assim como Church, ele também mostrou a existência de um problema indecidível em seu modelo - o problema da parada.

Church, Turing e Kleene formalmente demonstraram que os três sistemas são equivalentes, e que descrevem exatamente a mesma classe de funções computáveis. Tal prova é a base do que é hoje conhecido como a tese de Church-Turing, que descreve que qualquer modelo computacional capaz de calcular tal classe de funções deve ser equivalente a uma máquina de Turing (ou uma função no cálculo lambda). Apesar de não provada, a tese é corroborada por inúmeras tentativas futuras infrutíferas de descrever modelos de computação "mais efetivos", como Autômatos celulares, máquinas de registro, lógica combinatória, algoritmos de Markov, e outros: todos são equivalentes à máquinas de Turing e, consequentemente, ao cálculo lambda.

Em 1940, inspirando-se no trabalho de Russel, Church estendeu o cálculo lambda [cite:@Church1940] para incluir um sistema de tipos, conhecido como cálculo lambda simplesmente tipado, de forma a proibir termos que não normalizam (entram em /loop/ infinito ao avaliá-los), demonstrando que tal linguagem é fortemente normalizante, isto é, todas as computações terminam. Haskell Curry e William Howard estenderam esse trabalho, construindo relações diretas entre matemática construtiva e sistemas de tipo no cálculo lambda.

É importante aqui ressaltar a distinção entre matemática "tradicional" e a matemática construtiva: na matemática construtiva, é imperativo que toda prova que mostre a existência de um objeto faça-o por fornecendo uma receita - um /algoritmo/ - para construí-lo, o que é causa de grandes diferenças entre as abordagens nas provas. O tópico da lógica construtiva foi causa de muita controvérsia, cerne do debate entre Brouwer e Hilbert, onde Hilbert famosamente afirmou *(tradução livre?)* "Tirar o princípio do terceiro excluido de um matemático é como proibir um astrônomo de usar um telescópio, ou um boxeador de usar seus punhos. Proibir a afirmações existênciais e o princípio do terceiro excluido é equivalente a renunciar completamente a ciência matemática", [cite:@VanHeijenoort1967].

Lógicas construtivas são tradicionalmente chamadas de intuicionistas, e proibem ferramentas úteis como a lei do terceiro excluido ($P \wedge \neg P$) ou a eliminação da dupla negação ($\neg \neg P \rightarrow P$). De fato, aplicando semânticas exteriores à lógica intuicionista - denominadas álgebras de Heyting - é possível demonstrar que ambas as leis, junto de muitos outras tradições não construtivas, não podem ser provadas como tautologias, apesar de poderem serem usadas em casos específicos.

A correspondência de Curry-Howard explicita que o tipo de uma função pode ser diretamente correlacionado com o enunciado da prova, e a expressão do cálculo lambda por sua vez representa o corpo, ou o próprio algoritmo. Funções representam implicações, e a aplicação dessas - conhecido como redução $\beta$ - representam /modus ponens/. Nessa interpretação, termos no cálculo lambda simplesmente tipado podem ser visto como provas de fórmulas na lógica intuicionista implicacional. Dessa forma, fica claro que o ato de provar enunciados matemáticos pode ser reduzido a construir uma expressão no cálculo lambda com o tipo correspondente, que pode ser checado por algoritmos computacionais.

* System F 

# https://reasonablypolymorphic.com/blog/theorems-for-free/
# https://reasonablypolymorphic.com/blog/recursion-schemes/
# https://reasonablypolymorphic.com/blog/follow-the-denotation/
# https://xavierleroy.org/CdF/2018-2019/6.pdf).

O cálculo lambda simplesmente tipado é simples (sic.) demais para representar algoritmos usuais de maneira elegante. Por só permitir tipos simples (primitivos) e implicações entre esses, e por não permitir quantificar sobre predicados, é impossível escrever funções que aplicam-se a estruturas distintas. Por exemplo, a função ~quicksort~ tradicionalmente é escrita genericamente sobre uma sequência e um operador binário, mas isso não é possível no cálculo simplesmente tipado, e extensões a esse sistema fizeram-se necessárias. 

Jean-Yves Girard, em 1972 em sua tese de PhD., e John C. Reynolds, em 1974, descobriram independentemente as bases teóricas para um sistema de tipos que permite a quantificação universal sobre tipos, o cálculo lambda polimórfico, conhecido como /System F/. Esse sistema introduziu construtores universais sobre tipos, de modo a permitir funções generalizarem sobre os tipos de seus argumentos. Segundo Girard, o sistema fora desenvolvido explicitamente tendo em mente a correspondência de Curry-Howard, sendo a imagem isomórfica do cálculo proposicional intuicionista de segunda ordem [cite:@girard2011blind], visto que é fortemente normalizante - isto é, nenhum termo contém loops infinitos - e portanto é uma lógica /consistente/.

Apesar disso, inferência de tipos no caso geral é um problema indecidível nesse sistema, dado que termos possuem múltiplos tipos válidos. Por exemplo, a função identidade $\lambda x. x$ pode ser tipada como $int \rightarrow int$, $str \rightarrow str$  ou a versão generalizada $\Lambda \alpha, \alpha \rightarrow \alpha$, dependendo do contexto onde é aplicado. Uma restrição ao /System F/ foi desenvolvido por J. Roger Hindley, e depois redescoberto por Robin Milner, que tem a capacidade de inferir o tipo mais geral para qualquer termo de maneira eficiente, chamado de Algoritmo W.

Assim, o sistema de tipos Hindley-Milner se tornou base para inúmeras linguagens funcionais, como a família ML de linguagens, Haskell, e rencentemente a linguagem funcional Rust. Pelo sucesso da teoria, ela foi objeto de inúmeras extensões, como por exemplo, para permitir restrições de classes de tipos, uma forma de polimorfismo /ad-hoc/, em Haskell conhecidos como /type classes/ e em Rust conhecidos como /traits/. Entretanto, a extensão com maiores efeitos semânticos é a introdução de definições recursivas, para que essas linguagens se tornem mais práticas de se usar. Adicionar definições recursivas fazem com que a lógica dessas linguagens se torne inconsistente, visto que se torna possível construir termos de qualquer tipo utilizando loops infinitos. O problema de adicionar definições recursivas sem permitir que qualquer tipo se torne habitado é recorrente em quase todos os sistemas de tipos, e será revisto quando falarmos de tipos dependentes. 

Ainda que essas linguagens não possam ser usadas para provar teoremas interessantes, elas possuem características muito peculiares na área de verificação formal. Em /Theorems for Free/[cite:@10.1145/99370.99404], Wadler demonstrou que, dentro do /System F/, é possível deduzir propriedades sobre qualquer funções genérica sobre o tipo de seu argumento, sem sequer observar a implementação dessas. Por exemplo, é possível mostrar que uma função polimórfica de tipo $\forall T, T \rightarrow T$ necessariamente precisa ser isomórfica à função identidade $\Lambda T, \lambda (t: T), t$; isto é, não é possível implementar uma função desse tipo que não seja a função identidade.

Wadler foi além. Estendendo o sistema com um tipo genérico de listas $\Lambda T, [T]$, é possível provar propriedades não óbvias sobre funções paramétricas. Sendo $f: A \rightarrow B$, e $map\, f\, [x_1; \hdots; x_n] = [f\, x_1; \hdots,; f\, x_n]$, qualquer função $R: \Lambda T, [[T]]\rightarrow [T]$ deve satisfazer a seguinte igualdade:
$$
map\, f\, (R\, lists) = R\, (map\, (map\, f)\, lists)
$$

E de fato, uma função prática que satisfaz esse tipo é $concat: \Lambda T, [[T]] \rightarrow [T]$, que recebe uma listas de listas e concatena seus elementos em uma lista só.

Tais propriedades são chamadas de "Teoremas de graça" pois devem ser válidas pra qualquer função que satisfaça esses tipos, e são provadas utilizando uma semântica externa ao /System F/. Como esse sistema só permite que funções quantifiquem sobre tipos, não é possível utilizá-lo para provar teoremas sobre funções específicas. Para isso, faz-se necessário um sistema de tipos que permita que tipos quantifiquem sobre variáveis.

(Citar /System $F_{\omega}$/? Teoricamente /System F/ não deixa que tipos dependam de outros tipos, apenas funções.) 

* Tipos dependentes

O primeiro sistema que adotou sistemas de tipos com a intenção de verificação automatizada de provas foi o Automath [cite:@deBruijn1983]. Apesar de nunca ter tido o devido reconhecimento público, o sistema fora utilizado para verificar computacionalmente o livro /Foundations of Analysis/ [cite:@landau2001foundations], ainda em 1976.


* Bibliografia
#+PRINT_BIBLIOGRAPHY: 

* Local Variables :noexport:
# Local Variables:
# org-latex-pdf-process: ("latexmk -f -pdf %f")
# End:
